#!/bin/sh
# shellcheck disable=SC2155

role_name="role-name"
credentials="$(curl -m 1 -s http://169.254.169.254/latest/meta-data/iam/security-credentials/$role_name)"

get_key_value() {
  echo "$1" | grep "$2" | cut -d ':' -f 2 | cut -d '"' -f 2
}

if [ -n "$credentials" ]; then
    export AWS_ACCESS_KEY_ID=$(get_key_value "$credentials" "AccessKeyId")
    export AWS_SECRET_ACCESS_KEY=$(get_key_value "$credentials" "SecretAccessKey")
    export AWS_SESSION_TOKEN=$(get_key_value "$credentials" "Token")
fi
